# Nixpacks configuration for Railway
[phases.setup]
aptPkgs = ["gcc", "libpq-dev"]

[phases.build]
cmds = [
  "mkdir -p logs",
  "python manage.py collectstatic --noinput --clear"
]

[start]
cmd = "python manage.py check && gunicorn travelapi.wsgi:application -c gunicorn_conf.py"
