# Generated by Django 5.2.6 on 2025-09-28 14:28

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TravelPlanningSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_id', models.UUIDField(default=uuid.uuid4, unique=True)),
                ('user_email', models.EmailField(max_length=254)),
                ('destination', models.CharField(max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('travelers', models.CharField(max_length=50)),
                ('budget', models.CharField(max_length=50)),
                ('flight_search_requested', models.BooleanField(default=False)),
                ('hotel_search_requested', models.BooleanField(default=False)),
                ('flight_search_completed', models.BooleanField(default=False)),
                ('hotel_search_completed', models.BooleanField(default=False)),
                ('optimization_score', models.IntegerField(default=0)),
                ('total_estimated_cost', models.DecimalField(decimal_places=2, max_digits=10, null=True)),
                ('cost_efficiency', models.CharField(default='unknown', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='AgentExecutionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agent_type', models.CharField(choices=[('coordinator', 'Coordinator'), ('flight', 'Flight Agent'), ('hotel', 'Hotel Agent'), ('optimizer', 'Optimizer')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('input_data', models.JSONField()),
                ('output_data', models.JSONField(blank=True, null=True)),
                ('error_message', models.TextField(blank=True, null=True)),
                ('execution_time_ms', models.IntegerField(blank=True, null=True)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_logs', to='langgraph_agents.travelplanningsession')),
            ],
            options={
                'ordering': ['started_at'],
            },
        ),
    ]
