# Generated by Django 5.2.6 on 2025-11-07 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('langgraph_agents', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='agentexecutionlog',
            options={'ordering': ['started_at'], 'verbose_name': 'Agent Execution Log', 'verbose_name_plural': 'Agent Execution Logs'},
        ),
        migrations.AlterModelOptions(
            name='travelplanningsession',
            options={'ordering': ['-created_at'], 'verbose_name': 'Travel Planning Session', 'verbose_name_plural': 'Travel Planning Sessions'},
        ),
        migrations.AddIndex(
            model_name='agentexecutionlog',
            index=models.Index(fields=['session'], name='idx_log_session'),
        ),
        migrations.AddIndex(
            model_name='agentexecutionlog',
            index=models.Index(fields=['agent_type'], name='idx_log_agent_type'),
        ),
        migrations.AddIndex(
            model_name='agentexecutionlog',
            index=models.Index(fields=['status'], name='idx_log_status'),
        ),
        migrations.AddIndex(
            model_name='agentexecutionlog',
            index=models.Index(fields=['started_at'], name='idx_log_started'),
        ),
        migrations.AddIndex(
            model_name='agentexecutionlog',
            index=models.Index(fields=['session', 'agent_type'], name='idx_session_agent'),
        ),
        migrations.AddIndex(
            model_name='agentexecutionlog',
            index=models.Index(fields=['session', 'status'], name='idx_session_status_log'),
        ),
        migrations.AddIndex(
            model_name='travelplanningsession',
            index=models.Index(fields=['user_email'], name='idx_session_email'),
        ),
        migrations.AddIndex(
            model_name='travelplanningsession',
            index=models.Index(fields=['status'], name='idx_session_status'),
        ),
        migrations.AddIndex(
            model_name='travelplanningsession',
            index=models.Index(fields=['destination'], name='idx_session_dest'),
        ),
        migrations.AddIndex(
            model_name='travelplanningsession',
            index=models.Index(fields=['created_at'], name='idx_session_created'),
        ),
        migrations.AddIndex(
            model_name='travelplanningsession',
            index=models.Index(fields=['session_id'], name='idx_session_id'),
        ),
        migrations.AddIndex(
            model_name='travelplanningsession',
            index=models.Index(fields=['user_email', 'status'], name='idx_email_status'),
        ),
        migrations.AddIndex(
            model_name='travelplanningsession',
            index=models.Index(fields=['user_email', 'created_at'], name='idx_email_created'),
        ),
        migrations.AddIndex(
            model_name='travelplanningsession',
            index=models.Index(fields=['status', 'created_at'], name='idx_status_created'),
        ),
    ]
